import { ThirdwebProvider } from "@thirdweb-dev/react";
import { CHAIN } from "../const/chains";
import { Inter } from "next/font/google";
import { Nav } from "../components/Navbar";
import Head from "next/head";
import "../styles/globals.css";
import type { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className={inter.className}>
      <Head>
        <title>TradewithNFTs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThirdwebProvider
          // Set active chain for app
          activeChain={{

            chainId: 1001, // Chain ID of the network
            // Array of RPC URLs to use
            rpc: ["https://public-en-baobab.klaytn.net"],
    
            // === Information for adding the network to your wallet (how it will appear for first time users) === \\
            // Information about the chain's native currency (i.e. the currency that is used to pay for gas)
            nativeCurrency: {
              decimals: 18,
              name: "Klaytn Testnet",
              symbol: "KLAY",
            },
            shortName: "Klaytn Testnet", // Display value shown in the wallet UI
            slug: "klatyntestnet", // Display value shown in the wallet UI
            testnet: true, // Boolean indicating whether the chain is a testnet or mainnet
            chain: "Klaytn Testnet", // Name of the network
            name: "Klaytn Testnet", // Name of the network
          }}
          // Auth (SIWE) configuration
          authConfig={{
            domain: process.env.NEXT_PUBLIC_AUTH_DOMAIN || "evmkit.com", // Your website domain
            authUrl: "/api/auth", // API Route (default is - pages/api/auth/[...thirdweb].ts)
          }}
          clientId={process.env.NEXT_PUBLIC_THIRDWEB_API_KEY}
        >
          <Nav />
          <Component {...pageProps} />
        </ThirdwebProvider>
      </main>
    </div>
  );
}

export default MyApp;
